env:
  GO111MODULE: on

tasks:
  test:
    cmd: go test -v ./...

  build:
    cmd: go build -o bin/workflow cmd/workflow/main.go

commands:
  test:
    workflow:
    - run: test

  build:
    workflow:
    - run: test

    - run: build
      when:
      - test.succeeded
