env:
  GO111MODULE: on

tasks:
  test:
    cmd: go test -v ./...

  build:
    cmd: go build -o bin/workflow cmd/workflow/main.go

workflow:
  test:
  - run: test

  build:
  - run: test

  - run: build
