env:
  GO111MODULE: on

vars:
  test: &test go test -v ./...

commands:
  test:
    workflow:
    - name: test
      cmd: *test

  build:
    workflow:
    - name: test
      cmd: *test

    - name: build
      cmd: go build -o bin/workflow cmd/workflow/main.go
      when:
      - test.succeeded
