env:
  GO111MODULE: on

vars:
  test: &test go test -v ./...
  build: &build go build -o bin/workflow cmd/workflow/main.go

commands:
  test:
    workflow:
    - cmd: *test

  build:
    workflow:
    - cmd: *test

    - cmd: *build
      when:
      - test.succeeded
